My Project: H5::CommonFG Class Reference
H5::CommonFG Class Reference
CommonFG is an abstract base class of H5Group.
#include <H5CommonFG.h>
Public Member Functions
DataType openDataType (const char *name) const
Opens the named generic datatype at this location.
DataType openDataType (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
ArrayType openArrayType (const char *name) const
Opens the named array datatype at this location.
ArrayType openArrayType (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
CompType openCompType (const char *name) const
Opens the named compound datatype at this location.
CompType openCompType (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
EnumType openEnumType (const char *name) const
Opens the named enumeration datatype at this location.
EnumType openEnumType (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
IntType openIntType (const char *name) const
Opens the named integer datatype at this location.
IntType openIntType (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
FloatType openFloatType (const char *name) const
Opens the named floating-point datatype at this location.
FloatType openFloatType (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
StrType openStrType (const char *name) const
Opens the named string datatype at this location.
StrType openStrType (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
VarLenType openVarLenType (const char *name) const
Opens the named variable length datatype at this location.
VarLenType openVarLenType (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
Member Function Documentation
openArrayType() [1/2]
ArrayType H5::CommonFG::openArrayType (const char * name) const
Parameters
name - IN: Name of the array datatype to open
Returns
ArrayType instance
Exceptions
H5::FileIException or H5::GroupIException
Referenced by openArrayType().
openArrayType() [2/2]
ArrayType H5::CommonFG::openArrayType (const H5std_string & name) const
References openArrayType().
openCompType() [1/2]
CompType H5::CommonFG::openCompType (const char * name) const
Parameters
name - IN: Name of the compound datatype to open
Returns
CompType instance
Exceptions
H5::FileIException or H5::GroupIException
Referenced by openCompType().
openCompType() [2/2]
CompType H5::CommonFG::openCompType (const H5std_string & name) const
References openCompType().
openDataType() [1/2]
DataType H5::CommonFG::openDataType (const char * name) const
Parameters
name - IN: Name of the datatype to open
Returns
DataType instance
Exceptions
H5::FileIException or H5::GroupIException
Referenced by openDataType().
openDataType() [2/2]
DataType H5::CommonFG::openDataType (const H5std_string & name) const
References openDataType().
openEnumType() [1/2]
EnumType H5::CommonFG::openEnumType (const char * name) const
Parameters
name - IN: Name of the enumeration datatype to open
Returns
EnumType instance
Exceptions
H5::FileIException or H5::GroupIException
Referenced by openEnumType().
openEnumType() [2/2]
EnumType H5::CommonFG::openEnumType (const H5std_string & name) const
References openEnumType().
openFloatType() [1/2]
FloatType H5::CommonFG::openFloatType (const char * name) const
Parameters
name - IN: Name of the floating-point datatype to open
Returns
FloatType instance
Exceptions
H5::FileIException or H5::GroupIException
Referenced by openFloatType().
openFloatType() [2/2]
FloatType H5::CommonFG::openFloatType (const H5std_string & name) const
References openFloatType().
openIntType() [1/2]
IntType H5::CommonFG::openIntType (const char * name) const
Parameters
name - IN: Name of the integer datatype to open
Returns
IntType instance
Exceptions
H5::FileIException or H5::GroupIException
Referenced by openIntType().
openIntType() [2/2]
IntType H5::CommonFG::openIntType (const H5std_string & name) const
References openIntType().
openStrType() [1/2]
StrType H5::CommonFG::openStrType (const char * name) const
Parameters
name - IN: Name of the string datatype to open
Returns
StrType instance
Exceptions
H5::FileIException or H5::GroupIException
Referenced by openStrType().
openStrType() [2/2]
StrType H5::CommonFG::openStrType (const H5std_string & name) const
References openStrType().
openVarLenType() [1/2]
VarLenType H5::CommonFG::openVarLenType (const char * name) const
Parameters
name - IN: Name of the variable length datatype to open
Returns
VarLenType instance
Exceptions
H5::FileIException or H5::GroupIException
Referenced by openVarLenType().
openVarLenType() [2/2]
VarLenType H5::CommonFG::openVarLenType (const H5std_string & name) const
References openVarLenType().
The documentation for this class was generated from the following files:
H5CommonFG.h
H5CommonFG.cpp
The HDF Group Help Desk:
Copyright by The HDF Group
and the Board of Trustees of the University of Illinois