My Project: H5::ArrayType Class Reference
H5::ArrayType Class Reference
Class ArrayType inherits from DataType and provides wrappers for the HDF5's Array Datatypes.
#include <H5ArrayType.h>
Public Member Functions
ArrayType (const DataType &base_type, int ndims, const hsize_t *dims)
Creates a new array data type based on the specified base_type.
ArrayType & operator= (const ArrayType &rhs)
Assignment operator.
ArrayType (const H5Location &loc, const char *name)
Creates an ArrayType instance by opening an HDF5 array datatype given its name, provided as a C character string.
ArrayType (const H5Location &loc, const H5std_string &name)
Creates an ArrayType instance by opening an HDF5 array datatype given its name, provided as an H5std_string.
virtual DataType * decode () const
Returns an ArrayType object via DataType* by decoding the binary object description of this type.
int getArrayNDims () const
Returns the number of dimensions for an array datatype.
int getArrayDims (hsize_t *dims) const
Retrieves the size of all dimensions of an array datatype.
virtual H5std_string fromClass () const
Returns this class name.
ArrayType (const ArrayType &original)
Copy constructor: same HDF5 object as original.
ArrayType (const hid_t existing_id)
Creates an ArrayType object using an existing id.
virtual ~ArrayType ()
Properly terminates access to this array datatype.
ArrayType ()
Default constructor: Creates a stub ArrayType.
Public Member Functions inherited from H5::DataType
DataType (const H5T_class_t type_class, size_t size)
Creates a object given its class and size.
DataType (const DataType &original)
Copy constructor: same HDF5 object as original.
DataType (const PredType &pred_type)
Creates a DataType instance using a predefined type.
DataType (const H5Location &loc, const char *name)
Creates a DataType instance by opening an HDF5 datatype given its name as a char*.
DataType (const H5Location &loc, const H5std_string &name)
Creates a DataType instance by opening an HDF5 datatype given its name as an H5std_string.
DataType (const H5Location &loc, const void *ref, H5R_type_t ref_type=H5R_OBJECT, const PropList &plist=PropList::DEFAULT)
Given a reference, ref, to an hdf5 group, creates a DataType object.
virtual void close ()
Closes the datatype if it is not a predefined type.
void copy (const DataType &like_type)
Copies an existing datatype to this datatype object.
void copy (const DataSet &dset)
Copies the datatype of the given dataset to this datatype object.
void encode ()
Creates a binary object description of this datatype.
H5T_class_t getClass () const
Returns the datatype class identifier.
void commit (const H5Location &loc, const char *name)
Commits a transient datatype to a file, creating a new named datatype.
void commit (const H5Location &loc, const H5std_string &name)
This is an overloaded member function, provided for convenience. It differs from the above function only in the type of the argument name.
bool committed () const
Determines whether a datatype is a named type or a transient type.
H5T_conv_t find (const DataType &dest, H5T_cdata_t **pcdata) const
Finds a conversion function that can handle a conversion from this datatype to the specified datatype, dest.
void convert (const DataType &dest, size_t nelmts, void *buf, void *background, const PropList &plist=PropList::DEFAULT) const
Converts data from this datatype to the specified datatypes.
DataType & operator= (const DataType &rhs)
Assignment operator.
bool operator== (const DataType &compared_type) const
Compares this DataType against the given one to determines whether the two objects refer to the same actual datatype.
bool operator!= (const DataType &compared_type) const
Compares this DataType against the given one to determines whether the two objects refer to different actual datatypes.
void lock () const
Locks a datatype, making it read-only and non-destructible.
size_t getSize () const
Returns the size of a datatype.
DataType getSuper () const
Returns the base datatype from which a datatype is derived.
void registerFunc (H5T_pers_t pers, const char *name, const DataType &dest, H5T_conv_t func) const
Registers the specified conversion function.
void registerFunc (H5T_pers_t pers, const H5std_string &name, const DataType &dest, H5T_conv_t func) const
This is an overloaded member function, provided for convenience. It differs from the above function only in the type of the argument name.
void unregister (H5T_pers_t pers, const char *name, const DataType &dest, H5T_conv_t func) const
Removes a conversion function from all conversion paths.
void unregister (H5T_pers_t pers, const H5std_string &name, const DataType &dest, H5T_conv_t func) const
This is an overloaded member function, provided for convenience. It differs from the above function only in the type of the argument name.
void setTag (const char *tag) const
Tags an opaque datatype.
void setTag (const H5std_string &tag) const
This is an overloaded member function, provided for convenience. It differs from the above function only in the type of the argument name.
H5std_string getTag () const
Gets the tag associated with an opaque datatype.
bool detectClass (H5T_class_t cls) const
Checks whether a datatype contains (or is) a certain type of datatype.
bool isVariableStr () const
Check whether this datatype is a variable-length string.
PropList getCreatePlist () const
Returns a copy of the property list, which is for datatype creation.
DataType (const hid_t type_id)
Creates a datatype using an existing datatype's id.
DataType ()
Default constructor: Creates a stub datatype.
bool hasBinaryDesc () const
Determines whether this datatype has a binary object description.
virtual hid_t getId () const
Get the id of this datatype.
virtual ~DataType ()
Properly terminates access to this datatype.
Public Member Functions inherited from H5::H5Object
Attribute createAttribute (const char *name, const DataType &type, const DataSpace &space, const PropList &create_plist=PropList::DEFAULT) const
Creates an attribute for a group, dataset, or named datatype.
Attribute createAttribute (const H5std_string &name, const DataType &type, const DataSpace &space, const PropList &create_plist=PropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for name.
Attribute openAttribute (const char *name) const
Opens an attribute given its name.
Attribute openAttribute (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for name.
Attribute openAttribute (const unsigned int idx) const
Opens an attribute given its index.
int iterateAttrs (attr_operator_t user_op, unsigned *idx=NULL, void *op_data=NULL)
Iterates a user's function over all the attributes of an H5 object, which may be a group, dataset or named datatype.
void visit (H5_index_t idx_type, H5_iter_order_t order, visit_operator_t user_op, void *op_data, unsigned int fields)
Recursively visits all HDF5 objects accessible from this object.
unsigned objVersion () const
Returns the header version of this HDF5 object.
int getNumAttrs () const
Returns the number of attributes attached to this HDF5 object.
bool attrExists (const char *name) const
Checks whether the named attribute exists at this location.
bool attrExists (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for name.
void renameAttr (const char *oldname, const char *newname) const
Renames the named attribute from this object.
void renameAttr (const H5std_string &oldname, const H5std_string &newname) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for the names.
void removeAttr (const char *name) const
Removes the named attribute from this object.
void removeAttr (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for name.
ssize_t getObjName (char *obj_name, size_t buf_size=0) const
Given an id, returns the type of the object.
ssize_t getObjName (H5std_string &obj_name, size_t len=0) const
Gets the name of this object, returning its length.
H5std_string getObjName () const
Returns the name of this object as an H5std_string.
Public Member Functions inherited from H5::H5Location
bool nameExists (const char *name, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Checks if a link of a given name exists in a location.
bool nameExists (const H5std_string &name, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Checks if a link of a given name exists in a location.
bool exists (const char *name, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Deprecated in favor of nameExists.
bool exists (const H5std_string &name, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Deprecated in favor of nameExists.
void flush (H5F_scope_t scope) const
Flushes all buffers associated with a location to disk.
H5std_string getFileName () const
Gets the name of the file, in which an HDF5 object at this location belongs.
H5G_obj_t getObjType (void *ref, H5R_type_t ref_type=H5R_OBJECT) const
Retrieves the type of object that an object reference points to.
H5O_type_t getRefObjType (void *ref, H5R_type_t ref_type=H5R_OBJECT) const
Retrieves the type of object that an object reference points to.
void setComment (const char *name, const char *comment) const
Sets or resets the comment for an object specified by its name.
void setComment (const H5std_string &name, const H5std_string &comment) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name and comment.
void setComment (const char *comment) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it doesn't take an object name.
void setComment (const H5std_string &comment) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for comment.
ssize_t getComment (const char *name, size_t buf_size, char *comment) const
Retrieves the comment for this location, returning its length.
H5std_string getComment (const char *name, size_t buf_size=0) const
Returns the comment as string for this location, returning its length.
H5std_string getComment (const H5std_string &name, size_t buf_size=0) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void removeComment (const char *name) const
Removes the comment from an object specified by its name.
void removeComment (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void reference (void *ref, const char *name, H5R_type_t ref_type=H5R_OBJECT) const
This is an overloaded function, provided for your convenience. It differs from the above function in that it does not take a DataSpace object and the reference type must be specified.
void reference (void *ref, const H5std_string &name, H5R_type_t ref_type=H5R_OBJECT) const
This is an overloaded function, provided for your convenience. It differs from the above function in that it takes an H5std_string for the object's name.
void reference (void *ref, const char *name, const DataSpace &dataspace, H5R_type_t ref_type=H5R_DATASET_REGION) const
Creates a reference to an HDF5 object or a dataset region.
void reference (void *ref, const H5std_string &name, const DataSpace &dataspace, H5R_type_t ref_type=H5R_DATASET_REGION) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void dereference (const H5Location &loc, const void *ref, H5R_type_t ref_type=H5R_OBJECT, const PropList &plist=PropList::DEFAULT)
Dereferences a reference into an HDF5 object, given an HDF5 object.
DataSpace getRegion (void *ref, H5R_type_t ref_type=H5R_DATASET_REGION) const
Retrieves a dataspace with the region pointed to selected.
Group createGroup (const char *name, const LinkCreatPropList &lcpl) const
Creates a new group at this location, which can be a file, group, dataset, attribute, or named datatype.
Group createGroup (const H5std_string &name, const LinkCreatPropList &lcpl) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
Group createGroup (const char *name, size_t size_hint=0) const
Creates a new group at this location, which can be a file, group, dataset, attribute, or named datatype.
Group createGroup (const H5std_string &name, size_t size_hint=0) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
Group openGroup (const char *name) const
Opens an existing group in a location which can be a file or another group.
Group openGroup (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
DataSet createDataSet (const char *name, const DataType &data_type, const DataSpace &data_space, const DSetCreatPropList &create_plist=DSetCreatPropList::DEFAULT, const DSetAccPropList &dapl=DSetAccPropList::DEFAULT, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT) const
Creates a new dataset at this location.
DataSet createDataSet (const H5std_string &name, const DataType &data_type, const DataSpace &data_space, const DSetCreatPropList &create_plist=DSetCreatPropList::DEFAULT, const DSetAccPropList &dapl=DSetAccPropList::DEFAULT, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
DataSet openDataSet (const char *name, const DSetAccPropList &dapl=DSetAccPropList::DEFAULT) const
Opens an existing dataset at this location.
DataSet openDataSet (const H5std_string &name, const DSetAccPropList &dapl=DSetAccPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
H5L_info2_t getLinkInfo (const char *link_name, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Returns the information of the named link.
H5L_info2_t getLinkInfo (const H5std_string &link_name, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for link_name.
H5std_string getLinkval (const char *link_name, size_t size=0) const
Returns the name of the object that the symbolic link points to.
H5std_string getLinkval (const H5std_string &link_name, size_t size=0) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
hsize_t getNumObjs () const
Deprecated - moved to H5::Group in 1.10.2.
H5std_string getObjnameByIdx (hsize_t idx) const
Returns the name of an object in this group, given the object's index.
ssize_t getObjnameByIdx (hsize_t idx, char *name, size_t size) const
Retrieves the name of an object in this group, given the object's index.
ssize_t getObjnameByIdx (hsize_t idx, H5std_string &name, size_t size) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
H5O_type_t childObjType (const H5std_string &objname) const
This is an overloaded member function, provided for convenience. It takes an H5std_string for the object's name.
H5O_type_t childObjType (const char *objname) const
Returns the type of an object in this file/group, given the object's name.
H5O_type_t childObjType (hsize_t index, H5_index_t index_type=H5_INDEX_NAME, H5_iter_order_t order=H5_ITER_INC, const char *objname=".") const
Returns the type of an object in this file/group, given the object's index and its type and order.
unsigned childObjVersion (const char *objname) const
Returns the object header version of an object in this file/group, given the object's name.
unsigned childObjVersion (const H5std_string &objname) const
This is an overloaded member function, provided for convenience. It takes an H5std_string for the object's name.
void getObjinfo (H5O_info2_t &objinfo, unsigned fields=H5O_INFO_BASIC) const
Retrieves information about an HDF5 object.
void getObjinfo (const char *name, H5O_info2_t &objinfo, unsigned fields=H5O_INFO_BASIC, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Retrieves information about an HDF5 object given its name.
void getObjinfo (const H5std_string &name, H5O_info2_t &objinfo, unsigned fields=H5O_INFO_BASIC, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for name.
void getObjinfo (const char *grp_name, H5_index_t idx_type, H5_iter_order_t order, hsize_t idx, H5O_info2_t &objinfo, unsigned fields=H5O_INFO_BASIC, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Retrieves information about an HDF5 object given its index.
void getObjinfo (const H5std_string &grp_name, H5_index_t idx_type, H5_iter_order_t order, hsize_t idx, H5O_info2_t &objinfo, unsigned fields=H5O_INFO_BASIC, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for name.
void getNativeObjinfo (H5O_native_info_t &objinfo, unsigned fields=H5O_NATIVE_INFO_HDR) const
Retrieves native information about an HDF5 object.
void getNativeObjinfo (const char *name, H5O_native_info_t &objinfo, unsigned fields=H5O_NATIVE_INFO_HDR, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Retrieves native information about an HDF5 object given its name.
void getNativeObjinfo (const H5std_string &name, H5O_native_info_t &objinfo, unsigned fields=H5O_NATIVE_INFO_HDR, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for name.
void getNativeObjinfo (const char *grp_name, H5_index_t idx_type, H5_iter_order_t order, hsize_t idx, H5O_native_info_t &objinfo, unsigned fields=H5O_NATIVE_INFO_HDR, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Retrieves native information about an HDF5 object given its index.
void getNativeObjinfo (const H5std_string &grp_name, H5_index_t idx_type, H5_iter_order_t order, hsize_t idx, H5O_native_info_t &objinfo, unsigned fields=H5O_NATIVE_INFO_HDR, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for name.
H5G_obj_t getObjTypeByIdx (hsize_t idx) const
Returns the type of an object in this group, given the object's index.
H5G_obj_t getObjTypeByIdx (hsize_t idx, char *type_name) const
This is an overloaded member function, provided for convenience. It differs from the above function because it also provides the returned object type in text (char*)
H5G_obj_t getObjTypeByIdx (hsize_t idx, H5std_string &type_name) const
This is an overloaded member function, provided for convenience. It differs from the above function because it also provides the returned object type in text (H5std_string&)
void getObjinfo (const char *name, hbool_t follow_link, H5G_stat_t &statbuf) const
Returns information about an object.
void getObjinfo (const H5std_string &name, hbool_t follow_link, H5G_stat_t &statbuf) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void getObjinfo (const char *name, H5G_stat_t &statbuf) const
This is an overloaded member function, provided for convenience. It differs from the above functions in that it doesn't have the paramemter follow_link.
void getObjinfo (const H5std_string &name, H5G_stat_t &statbuf) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
int iterateElems (const char *name, int *idx, H5G_iterate_t op, void *op_data)
Iterates a user's function over the entries of a group.
int iterateElems (const H5std_string &name, int *idx, H5G_iterate_t op, void *op_data)
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void link (const char *target_name, const char *link_name, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Creates a soft link from link_name to target_name.
void link (const H5std_string &target_name, const H5std_string &link_name, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for target_name and link_name.
void link (const char *curr_name, const Group &new_loc, const char *new_name, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Creates a hard link from new_name to curr_name.
void link (const H5std_string &curr_name, const Group &new_loc, const H5std_string &new_name, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for curr_name and new_name.
void link (const char *curr_name, const hid_t same_loc, const char *new_name, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Creates a hard link from new_name to curr_name - can be used to pass in H5L_SAME_LOC.
void link (const H5std_string &curr_name, const hid_t same_loc, const H5std_string &new_name, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for curr_name and new_name.
void link (H5L_type_t link_type, const char *curr_name, const char *new_name) const
Creates a link of the specified type from new_name to curr_name.
void link (H5L_type_t link_type, const H5std_string &curr_name, const H5std_string &new_name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for curr_name and new_name.
void unlink (const char *link_name, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Removes the specified link from this group.
void unlink (const H5std_string &link_name, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void mount (const char *name, const H5File &child, const PropList &plist) const
Mounts the file child onto this group.
void mount (const H5std_string &name, const H5File &child, const PropList &plist) const
This is an overloaded member function, provided for convenience. It takes an H5std_string for name.
void unmount (const char *name) const
Unmounts the specified file.
void unmount (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void copyLink (const char *src_name, const Group &dst, const char *dst_name, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Copies a link from one group to another.
void copyLink (const H5std_string &src_name, const Group &dst, const H5std_string &dst_name, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for src_name and dst_name.
void copyLink (const char *src_name, const char *dst_name, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Copies a link from a group in the same location.
void copyLink (const H5std_string &src_name, const H5std_string &dst_name, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for src_name and dst_name.
void moveLink (const char *src_name, const Group &dst, const char *dst_name, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Renames a link in this group and moves it to a new location.
void moveLink (const H5std_string &src_name, const Group &dst, const H5std_string &dst_name, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for src_name and dst_name.
void moveLink (const char *src_name, const char *dst_name, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Renames a link in this group.
void moveLink (const H5std_string &src_name, const H5std_string &dst_name, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for src_name and dst_name.
void move (const char *src, const char *dst) const
Renames an object at this location. - Deprecated due to inadequate functionality.
void move (const H5std_string &src, const H5std_string &dst) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for src and dst. - Deprecated due to inadequate functionality.
virtual void throwException (const H5std_string &func_name, const H5std_string &msg) const
For subclasses, H5File and Group, to throw appropriate exception.
H5Location ()
Public Member Functions inherited from H5::IdComponent
void incRefCount (const hid_t obj_id) const
Increment reference counter for a given id.
void incRefCount () const
Increment reference counter for the id of this object.
void decRefCount (const hid_t obj_id) const
Decrement reference counter for a given id.
void decRefCount () const
Decrement reference counter for the id of this object.
int getCounter (const hid_t obj_id) const
Returns the reference counter for a given id.
int getCounter () const
Returns the reference counter for the id of this object.
H5I_type_t getHDFObjType () const
Returns the type of the object. It is an overloaded function of the above function.
IdComponent & operator= (const IdComponent &rhs)
Assignment operator.
void setId (const hid_t new_id)
Sets the identifier of this object to a new value.
virtual ~IdComponent ()
Noop destructor.
Additional Inherited Members
Static Public Member Functions inherited from H5::DataType
static bool detectClass (const PredType &pred_type, H5T_class_t cls)
Checks whether a predtype is a certain class of datatype.
Static Public Member Functions inherited from H5::IdComponent
static H5I_type_t getHDFObjType (const hid_t obj_id)
Given an id, returns the type of the object.
static hsize_t getNumMembers (H5I_type_t type)
Returns the number of members of the given type.
static bool isValid (hid_t an_id)
Checks if the given ID is valid.
static bool typeExists (H5I_type_t type)
Queries if a given type is currently registered with the library.
Protected Member Functions inherited from H5::H5Location
virtual ~H5Location ()
Noop destructor.
Constructor & Destructor Documentation
ArrayType() [1/6]
H5::ArrayType::ArrayType (const DataType & base_type, int ndims, const hsize_t * dims)
Parameters
base_type - IN: Existing datatype
ndims - IN: Rank of the array, [0..H5S_MAX_RANK]
dims - IN: Size of each array dimension
Exceptions
H5::DataTypeIException
References H5::DataType::getId().
ArrayType() [2/6]
H5::ArrayType::ArrayType (const H5Location & loc, const char * dtype_name)
Parameters
loc - IN: Location of the type
dtype_name - IN: Array type name
Exceptions
H5::DataTypeIException
ArrayType() [3/6]
H5::ArrayType::ArrayType (const H5Location & loc, const H5std_string & dtype_name)
Parameters
loc - IN: Location of the type
dtype_name - IN: Array type name
Exceptions
H5::DataTypeIException
ArrayType() [4/6]
H5::ArrayType::ArrayType (const ArrayType & original)
ArrayType() [5/6]
H5::ArrayType::ArrayType (const hid_t existing_id)
Parameters
existing_id - IN: Id of an existing datatype
Exceptions
H5::DataTypeIException
~ArrayType()
H5::ArrayType::~ArrayType () virtual
ArrayType() [6/6]
H5::ArrayType::ArrayType ()
Referenced by decode().
Member Function Documentation
decode()
DataType * H5::ArrayType::decode () const virtual
Exceptions
H5::DataTypeIException
Reimplemented from H5::DataType.
References ArrayType().
fromClass()
virtual H5std_string H5::ArrayType::fromClass () const inline virtual
Reimplemented from H5::DataType.
getArrayDims()
int H5::ArrayType::getArrayDims (hsize_t * dims) const
Parameters
dims - OUT: Sizes of dimensions
Returns
Number of dimensions
Exceptions
H5::DataTypeIException
getArrayNDims()
int H5::ArrayType::getArrayNDims () const
Returns
Number of dimensions
Exceptions
H5::DataTypeIException
operator=()
ArrayType & H5::ArrayType::operator= (const ArrayType & rhs)
Parameters
rhs - IN: Reference to the existing array datatype
Returns
Reference to ArrayType instance
Exceptions
H5::DataTypeIException
References H5::Exception::getDetailMsg(), and H5::IdComponent::setId().
The documentation for this class was generated from the following files:
H5ArrayType.h
H5ArrayType.cpp
The HDF Group Help Desk:
Copyright by The HDF Group
and the Board of Trustees of the University of Illinois