My Project: H5::PropList Class Reference
H5::PropList Class Reference
Class PropList inherits from IdComponent and provides wrappers for the HDF5 generic property list.
#include <H5PropList.h>
Public Member Functions
PropList (const hid_t plist_id)
Creates a property list using the id of an existing property.
PropList & operator= (const PropList &rhs)
Assignment operator.
bool operator== (const PropList &rhs) const
Compares this property list or class against the given list or class.
virtual void close ()
Closes the property list if it is not a default one.
void closeClass () const
Close a property list class.
void copy (const PropList &like_plist)
Makes a copy of an existing property list.
void copyProp (PropList &dest, const char *name) const
Copies a property from this property list or class to another.
void copyProp (PropList &dest, const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what arguments it accepts.
void copyProp (PropList &dest, PropList &src, const char *name) const
Copies a property from one list or class to another - Obsolete.
void copyProp (PropList &dest, PropList &src, const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what arguments it accepts. - Obsolete.
hid_t getClass () const
Returns the class of this property list, i.e. H5P_FILE_CREATE...
H5std_string getClassName () const
Return the name of a generic property list class.
PropList getClassParent () const
Returns the parent class of a generic property class.
size_t getNumProps () const
Returns the number of properties in this property list or class.
void getProperty (const char *name, void *value) const
Query the value of a property in a property list.
void getProperty (const H5std_string &name, void *value) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what arguments it accepts.
H5std_string getProperty (const char *name) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what arguments it accepts.
H5std_string getProperty (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what arguments it accepts.
void setProperty (const char *name, const char *charptr) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what arguments it accepts.
void setProperty (const char *name, const void *value) const
Set a property's value in a property list.
void setProperty (const char *name, const H5std_string &strg) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what arguments it accepts.
void setProperty (const H5std_string &name, const void *value) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what arguments it accepts.
void setProperty (const H5std_string &name, const H5std_string &strg) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what arguments it accepts.
void setProperty (const char *name, void *value) const
Deprecated due to missing const in prototype. (1.10.1)
void setProperty (const char *name, H5std_string &strg) const
Deprecated due to missing const in prototype. (1.10.1)
void setProperty (const H5std_string &name, void *value) const
Deprecated due to missing const in prototype. (1.10.1)
void setProperty (const H5std_string &name, H5std_string &strg) const
Deprecated due to missing const in prototype. (1.10.1)
size_t getPropSize (const char *name) const
Query the size of a property in a property list or class.
size_t getPropSize (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what arguments it accepts.
bool isAClass (const PropList &prop_class) const
Determines whether a property list is a certain class.
bool propExist (const char *name) const
Query the existence of a property in a property object.
bool propExist (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what arguments it accepts.
void removeProp (const char *name) const
Removes a property from a property list.
void removeProp (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what arguments it accepts.
virtual H5std_string fromClass () const
Returns this class name.
PropList ()
Default constructor: creates a stub property list object.
PropList (const PropList &original)
Copy constructor: same HDF5 object as original.
virtual hid_t getId () const
Get the id of this property list.
virtual ~PropList ()
Properly terminates access to this property list.
Public Member Functions inherited from H5::IdComponent
void incRefCount (const hid_t obj_id) const
Increment reference counter for a given id.
void incRefCount () const
Increment reference counter for the id of this object.
void decRefCount (const hid_t obj_id) const
Decrement reference counter for a given id.
void decRefCount () const
Decrement reference counter for the id of this object.
int getCounter (const hid_t obj_id) const
Returns the reference counter for a given id.
int getCounter () const
Returns the reference counter for the id of this object.
H5I_type_t getHDFObjType () const
Returns the type of the object. It is an overloaded function of the above function.
IdComponent & operator= (const IdComponent &rhs)
Assignment operator.
void setId (const hid_t new_id)
Sets the identifier of this object to a new value.
virtual ~IdComponent ()
Noop destructor.
Static Public Attributes
static const PropList & DEFAULT
Default property list.
Additional Inherited Members
Static Public Member Functions inherited from H5::IdComponent
static H5I_type_t getHDFObjType (const hid_t obj_id)
Given an id, returns the type of the object.
static hsize_t getNumMembers (H5I_type_t type)
Returns the number of members of the given type.
static bool isValid (hid_t an_id)
Checks if the given ID is valid.
static bool typeExists (H5I_type_t type)
Queries if a given type is currently registered with the library.
Constructor & Destructor Documentation
PropList() [1/3]
H5::PropList::PropList (const hid_t plist_id)
Parameters
plist_id - IN: Id of the existing property list
Exceptions
H5::PropListIException
PropList() [2/3]
H5::PropList::PropList ()
PropList() [3/3]
H5::PropList::PropList (const PropList & original)
Parameters
original - IN: The original property list to copy
References H5::IdComponent::incRefCount().
~PropList()
H5::PropList::~PropList () virtual
References close(), and H5::Exception::getDetailMsg().
Member Function Documentation
close()
void H5::PropList::close () virtual
Exceptions
H5::PropListIException
Referenced by copy(), and ~PropList().
closeClass()
void H5::PropList::closeClass () const
Exceptions
H5::PropListIException
Description
Releases memory and detaches a class from the property list class hierarchy.
copy()
void H5::PropList::copy (const PropList & like_plist)
Parameters
like_plist - IN: Reference to the existing property list
Exceptions
H5::PropListIException
References close(), H5::Exception::getDetailMsg(), and getId().
Referenced by operator=().
copyProp() [1/4]
void H5::PropList::copyProp (PropList & dest, const char * name) const
Parameters
dest - IN: Destination property list or class
name - IN: Name of the property to copy - char pointer
Exceptions
H5::PropListIException
References getId().
Referenced by copyProp().
copyProp() [2/4]
void H5::PropList::copyProp (PropList & dest, const H5std_string & name) const
Parameters
dest - IN: Destination property list or class
name - IN: Name of the property to copy - H5std_string
References copyProp().
copyProp() [3/4]
void H5::PropList::copyProp (PropList & dest, PropList & src, const char * name) const
Parameters
dest - IN: Destination property list or class
src - IN: Source property list or class
name - IN: Name of the property to copy - char pointer
Note
This member function will be removed in the next release
Exceptions
H5::PropListIException
References getId().
copyProp() [4/4]
void H5::PropList::copyProp (PropList & dest, PropList & src, const H5std_string & name) const
Parameters
dest - IN: Destination property list or class
src - IN: Source property list or class
name - IN: Name of the property to copy - H5std_string
References copyProp().
fromClass()
virtual H5std_string H5::PropList::fromClass () const inline virtual
Reimplemented in H5::FileAccPropList, H5::DSetCreatPropList, H5::DSetMemXferPropList, H5::FileCreatPropList, H5::ObjCreatPropList, H5::DSetAccPropList, H5::LinkAccPropList, and H5::LinkCreatPropList.
getClass()
hid_t H5::PropList::getClass () const
Returns
The property list class if it is not equal to H5P_ROOT
Exceptions
H5::PropListIException
getClassName()
H5std_string H5::PropList::getClassName () const
Returns
A string containing the class name, if success, otherwise, a NULL string.
getClassParent()
PropList H5::PropList::getClassParent () const
Returns
The parent class of a property class
Exceptions
H5::PropListIException
getId()
hid_t H5::PropList::getId () const virtual
Returns
Property list identifier
Referenced by H5::DataType::convert(), copy(), H5::H5Location::copyLink(), copyProp(), H5::H5Object::createAttribute(), H5::H5Location::createDataSet(), H5::H5Location::createGroup(), H5::H5Location::getLinkInfo(), H5::H5Location::getNativeObjinfo(), H5::Group::getObjId(), H5::H5Location::getObjinfo(), H5::H5File::getVFDHandle(), H5::H5File::isAccessible(), isAClass(), H5::H5Location::link(), H5::H5Location::mount(), H5::H5Location::moveLink(), H5::H5Location::nameExists(), H5::H5Location::openDataSet(), H5::H5File::openFile(), operator==(), H5::DataSet::read(), H5::FileAccPropList::setFamily(), H5::FileAccPropList::setSplit(), H5::H5Location::unlink(), H5::DataSet::vlenReclaim(), and H5::DataSet::write().
getNumProps()
size_t H5::PropList::getNumProps () const
Returns
Size of the property.
Exceptions
H5::PropListIException
getProperty() [1/4]
H5std_string H5::PropList::getProperty (const char * name) const
Parameters
name - IN: Name of property to query - char pointer
Returns
The property that is a H5std_string.
Exceptions
H5::PropListIException
References getPropSize().
getProperty() [2/4]
void H5::PropList::getProperty (const char * name, void * value) const
Parameters
name - IN: Name of property to query - char pointer
value - OUT: Pointer to the buffer for the property value
Exceptions
H5::PropListIException
Description
Retrieves a copy of the value for a property in a property list. The property name must exist or this routine will throw an exception.
Referenced by getProperty().
getProperty() [3/4]
H5std_string H5::PropList::getProperty (const H5std_string & name) const
Parameters
name - IN: Name of property to query - H5std_string
Returns
The property that is a H5std_string.
References getProperty().
getProperty() [4/4]
void H5::PropList::getProperty (const H5std_string & name, void * value) const
Parameters
name - IN: Name of property to query - H5std_string
value - OUT: Pointer to the buffer for the property value
References getProperty().
getPropSize() [1/2]
size_t H5::PropList::getPropSize (const char * name) const
Parameters
name - IN: Name of property to query
Returns
Size of the property
Exceptions
H5::PropListIException
Description
This routine retrieves the size of a property's value in bytes. Zero-sized properties are allowed and the return value will be of 0. This function works for both property lists and classes.
Referenced by getProperty(), and getPropSize().
getPropSize() [2/2]
size_t H5::PropList::getPropSize (const H5std_string & name) const
Parameters
name - IN: Name of property to query - H5std_string
References getPropSize().
isAClass()
bool H5::PropList::isAClass (const PropList & prop_class) const
Parameters
prop_class - IN: Property class to query
Returns
true if the property list is a member of the property list class, and false, otherwise.
Exceptions
H5::PropListIException
References getId().
operator=()
PropList & H5::PropList::operator= (const PropList & rhs)
Parameters
rhs - IN: Reference to the existing property list
Returns
Reference to PropList instance
Exceptions
H5::PropListIException
References copy().
operator==()
bool H5::PropList::operator== (const PropList & rhs) const
Parameters
rhs - IN: Reference to the property list to compare
Returns
true if the property lists or classes are equal, and false, otherwise.
Exceptions
H5::PropListIException
References getId().
propExist() [1/2]
bool H5::PropList::propExist (const char * name) const
Queries the existence of a property in a property object.
Parameters
name - IN: Name of property to check for - char pointer
Returns
true if the property exists in the property object, and false, otherwise.
Exceptions
H5::PropListIException
Description
This routine checks if a property exists within a property list or class.
Referenced by propExist().
propExist() [2/2]
bool H5::PropList::propExist (const H5std_string & name) const
Parameters
name - IN: Name of property to check for - H5std_string
References propExist().
removeProp() [1/2]
void H5::PropList::removeProp (const char * name) const
Parameters
name - IN: Name of property to remove - char pointer
Exceptions
H5::PropListIException
Referenced by removeProp().
removeProp() [2/2]
void H5::PropList::removeProp (const H5std_string & name) const
Parameters
name - IN: Name of property to remove - H5std_string
References removeProp().
setProperty() [1/9]
void H5::PropList::setProperty (const char * name, const char * charptr) const
Parameters
name - IN: Name of property to set - char pointer
charptr - IN: Char pointer to the value for the property
Referenced by setProperty().
setProperty() [2/9]
void H5::PropList::setProperty (const char * name, const H5std_string & strg) const
Parameters
name - IN: Name of property to set - char pointer
strg - IN: Value for the property is a H5std_string
References setProperty().
setProperty() [3/9]
void H5::PropList::setProperty (const char * name, const void * value) const
Parameters
name - IN: Name of property to set - char pointer
value - IN: Void pointer to the value for the property
Exceptions
H5::PropListIException
setProperty() [4/9]
void H5::PropList::setProperty (const char * name, H5std_string & strg) const
References setProperty().
setProperty() [5/9]
void H5::PropList::setProperty (const char * name, void * value) const
setProperty() [6/9]
void H5::PropList::setProperty (const H5std_string & name, const H5std_string & strg) const
Parameters
name - IN: Name of property to set - H5std_string
strg - IN: Value for the property is a H5std_string
References setProperty().
setProperty() [7/9]
void H5::PropList::setProperty (const H5std_string & name, const void * value) const
Parameters
name - IN: Name of property to set - H5std_string
value - IN: Void pointer to the value for the property
References setProperty().
setProperty() [8/9]
void H5::PropList::setProperty (const H5std_string & name, H5std_string & strg) const
References setProperty().
setProperty() [9/9]
void H5::PropList::setProperty (const H5std_string & name, void * value) const
References setProperty().
Member Data Documentation
DEFAULT
const PropList& H5::PropList::DEFAULT static
The documentation for this class was generated from the following files:
H5PropList.h
H5PropList.cpp
The HDF Group Help Desk:
Copyright by The HDF Group
and the Board of Trustees of the University of Illinois