My Project: H5::IdComponent Class Reference
H5::IdComponent Class Reference
Class IdComponent provides wrappers of the C functions that operate on an HDF5 identifier.
#include <H5IdComponent.h>
Public Member Functions
void incRefCount (const hid_t obj_id) const
Increment reference counter for a given id.
void incRefCount () const
Increment reference counter for the id of this object.
void decRefCount (const hid_t obj_id) const
Decrement reference counter for a given id.
void decRefCount () const
Decrement reference counter for the id of this object.
int getCounter (const hid_t obj_id) const
Returns the reference counter for a given id.
int getCounter () const
Returns the reference counter for the id of this object.
H5I_type_t getHDFObjType () const
Returns the type of the object. It is an overloaded function of the above function.
IdComponent & operator= (const IdComponent &rhs)
Assignment operator.
void setId (const hid_t new_id)
Sets the identifier of this object to a new value.
virtual ~IdComponent ()
Noop destructor.
Static Public Member Functions
static H5I_type_t getHDFObjType (const hid_t obj_id)
Given an id, returns the type of the object.
static hsize_t getNumMembers (H5I_type_t type)
Returns the number of members of the given type.
static bool isValid (hid_t an_id)
Checks if the given ID is valid.
static bool typeExists (H5I_type_t type)
Queries if a given type is currently registered with the library.
Detailed Description
In most cases, the C library handles these operations and an application rarely needs them.
Constructor & Destructor Documentation
~IdComponent()
H5::IdComponent::~IdComponent () virtual
Member Function Documentation
decRefCount() [1/2]
void H5::IdComponent::decRefCount () const
decRefCount() [2/2]
void H5::IdComponent::decRefCount (const hid_t obj_id) const
getCounter() [1/2]
int H5::IdComponent::getCounter () const
Returns
Reference count
getCounter() [2/2]
int H5::IdComponent::getCounter (const hid_t obj_id) const
Returns
Reference count
getHDFObjType() [1/2]
H5I_type_t H5::IdComponent::getHDFObjType () const
Returns
a valid HDF object type, which may be one of the following:
H5I_FILE
H5I_GROUP
H5I_DATATYPE
H5I_DATASPACE
H5I_DATASET
H5I_ATTR
or H5I_BADID, if no valid type can be determined or the input object id is invalid.
getHDFObjType() [2/2]
H5I_type_t H5::IdComponent::getHDFObjType (const hid_t obj_id) static
Returns
a valid HDF object type, which may be one of the following:
H5I_FILE
H5I_GROUP
H5I_DATATYPE
H5I_DATASPACE
H5I_DATASET
H5I_ATTR
or H5I_BADID, if no valid type can be determined or the input object id is invalid.
getNumMembers()
hsize_t H5::IdComponent::getNumMembers (H5I_type_t type) static
Returns
Number of members
Description
If there is no member of the given type, getNumMembers will return 0. Valid types are:
H5I_FILE (= 1)
H5I_GROUP
H5I_DATATYPE
H5I_DATASPACE
H5I_DATASET
H5I_ATTR
H5I_VFL
H5I_VOL
H5I_GENPROP_CLS
H5I_GENPROP_LST
H5I_ERROR_CLASS
H5I_ERROR_MSG
H5I_ERROR_STACK
incRefCount() [1/2]
void H5::IdComponent::incRefCount () const
Referenced by H5::Attribute::Attribute(), H5::DataSet::DataSet(), H5::DataSpace::DataSpace(), H5::DataType::DataType(), H5::Group::Group(), H5::H5File::H5File(), H5::PropList::PropList(), and setId().
incRefCount() [2/2]
void H5::IdComponent::incRefCount (const hid_t obj_id) const
isValid()
bool H5::IdComponent::isValid (hid_t an_id) static
Returns
true if the given identifier is valid, and false, otherwise.
Description
A valid ID is one that is in use and has an application reference count of at least 1.
operator=()
IdComponent & H5::IdComponent::operator= (const IdComponent & rhs)
Parameters
rhs - IN: Reference to the existing object
Returns
Reference to IdComponent instance
Exceptions
H5::IdComponentException when attempt to close the HDF5 object fails
References H5::Exception::getDetailMsg(), and setId().
setId()
void H5::IdComponent::setId (const hid_t new_id)
Parameters
new_id - IN: New identifier to be set to
Exceptions
H5::IdComponentException when the attempt to close the HDF5 object fails
References incRefCount().
Referenced by H5::ArrayType::operator=(), operator=(), H5::DataType::operator=(), and H5::DataSet::operator=().
typeExists()
bool H5::IdComponent::typeExists (H5I_type_t type) static
Returns
true if the given type exists, and false, otherwise.
Description
Valid types are:
H5I_FILE (= 1)
H5I_GROUP
H5I_DATATYPE
H5I_DATASPACE
H5I_DATASET
H5I_ATTR
H5I_VFL
H5I_VOL
H5I_GENPROP_CLS
H5I_GENPROP_LST
H5I_ERROR_CLASS
H5I_ERROR_MSG
H5I_ERROR_STACK
The documentation for this class was generated from the following files:
H5IdComponent.h
H5IdComponent.cpp
The HDF Group Help Desk:
Copyright by The HDF Group
and the Board of Trustees of the University of Illinois