HDF5 C++ API: H5::H5Object Class Reference
H5::H5Object Class Reference abstract
Class H5Object is a bridge between H5Location and DataSet, DataType, and Group.
#include <H5Object.h>
Public Member Functions
Attribute createAttribute (const char *name, const DataType &type, const DataSpace &space, const PropList &create_plist=PropList::DEFAULT) const
Creates an attribute for a group, dataset, or named datatype.
Attribute createAttribute (const H5std_string &name, const DataType &type, const DataSpace &space, const PropList &create_plist=PropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for name.
Attribute openAttribute (const char *name) const
Opens an attribute given its name.
Attribute openAttribute (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for name.
Attribute openAttribute (const unsigned int idx) const
Opens an attribute given its index.
int iterateAttrs (attr_operator_t user_op, unsigned *idx=NULL, void *op_data=NULL)
Iterates a user's function over all the attributes of an H5 object, which may be a group, dataset or named datatype.
unsigned objVersion () const
Returns the header version of this HDF5 object.
bool attrExists (const char *name) const
Checks whether the named attribute exists at this location.
bool attrExists (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for name.
void renameAttr (const char *oldname, const char *newname) const
Renames the named attribute from this object.
void renameAttr (const H5std_string &oldname, const H5std_string &newname) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for the names.
void removeAttr (const char *name) const
Removes the named attribute from this object.
void removeAttr (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for name.
virtual hid_t getId () const =0
Public Member Functions inherited from H5::H5Location
bool exists (const char *name, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Checks if a link of a given name exists in a location.
bool exists (const H5std_string &name, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Checks if a link of a given name exists in a location.
void flush (H5F_scope_t scope) const
Flushes all buffers associated with a location to disk.
H5std_string getFileName () const
Gets the name of the file, in which this HDF5 object belongs.
H5G_obj_t getObjType (void *ref, H5R_type_t ref_type=H5R_OBJECT) const
Retrieves the type of object that an object reference points to.
H5O_type_t getRefObjType (void *ref, H5R_type_t ref_type=H5R_OBJECT) const
Retrieves the type of object that an object reference points to.
void setComment (const char *name, const char *comment) const
Sets or resets the comment for an object specified by its name.
void setComment (const H5std_string &name, const H5std_string &comment) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name and comment.
void setComment (const char *comment) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it doesn't take an object name.
void setComment (const H5std_string &comment) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for comment.
ssize_t getComment (const char *name, size_t buf_size, char *comment) const
Retrieves the comment for this location, returning its length.
H5std_string getComment (const char *name, size_t buf_size=0) const
Returns the comment as string for this location, returning its length.
H5std_string getComment (const H5std_string &name, size_t buf_size=0) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void removeComment (const char *name) const
Removes the comment from an object specified by its name.
void removeComment (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void reference (void *ref, const char *name, H5R_type_t ref_type=H5R_OBJECT) const
This is an overloaded function, provided for your convenience. It differs from the above function in that it does not take a DataSpace object and the reference type must be specified.
void reference (void *ref, const H5std_string &name, H5R_type_t ref_type=H5R_OBJECT) const
This is an overloaded function, provided for your convenience. It differs from the above function in that it takes an H5std_string for the object's name.
void reference (void *ref, const char *name, const DataSpace &dataspace, H5R_type_t ref_type=H5R_DATASET_REGION) const
Creates a reference to an HDF5 object or a dataset region.
void reference (void *ref, const H5std_string &name, const DataSpace &dataspace, H5R_type_t ref_type=H5R_DATASET_REGION) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void dereference (const H5Location &loc, const void *ref, H5R_type_t ref_type=H5R_OBJECT, const PropList &plist=PropList::DEFAULT)
Dereferences a reference into an HDF5 object, given an HDF5 object.
DataSpace getRegion (void *ref, H5R_type_t ref_type=H5R_DATASET_REGION) const
Retrieves a dataspace with the region pointed to selected.
Group createGroup (const char *name, size_t size_hint=0) const
Creates a new group at this location which can be a file or another group.
Group createGroup (const H5std_string &name, size_t size_hint=0) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
Group openGroup (const char *name) const
Opens an existing group in a location which can be a file or another group.
Group openGroup (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
DataSet createDataSet (const char *name, const DataType &data_type, const DataSpace &data_space, const DSetCreatPropList &create_plist=DSetCreatPropList::DEFAULT) const
Creates a new dataset at this location.
DataSet createDataSet (const H5std_string &name, const DataType &data_type, const DataSpace &data_space, const DSetCreatPropList &create_plist=DSetCreatPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
DataSet openDataSet (const char *name) const
Opens an existing dataset at this location.
DataSet openDataSet (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
H5std_string getLinkval (const char *link_name, size_t size=0) const
Returns the name of the object that the symbolic link points to.
H5std_string getLinkval (const H5std_string &link_name, size_t size=0) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
int getNumAttrs () const
Returns the number of attributes attached to this HDF5 object.
H5std_string getObjnameByIdx (hsize_t idx) const
Returns the name of an object in this group, given the object's index.
ssize_t getObjnameByIdx (hsize_t idx, char *name, size_t size) const
Retrieves the name of an object in this group, given the object's index.
ssize_t getObjnameByIdx (hsize_t idx, H5std_string &name, size_t size) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
H5O_type_t childObjType (const H5std_string &objname) const
This is an overloaded member function, provided for convenience. It takes an H5std_string for the object's name.
H5O_type_t childObjType (const char *objname) const
Returns the type of an object in this file/group, given the object's name.
H5O_type_t childObjType (hsize_t index, H5_index_t index_type=H5_INDEX_NAME, H5_iter_order_t order=H5_ITER_INC, const char *objname=".") const
Returns the type of an object in this file/group, given the object's index and its type and order.
unsigned childObjVersion (const char *objname) const
Returns the object header version of an object in this file/group, given the object's name.
unsigned childObjVersion (const H5std_string &objname) const
This is an overloaded member function, provided for convenience. It takes an H5std_string for the object's name.
H5G_obj_t getObjTypeByIdx (hsize_t idx) const
Returns the type of an object in this group, given the object's index.
H5G_obj_t getObjTypeByIdx (hsize_t idx, char *type_name) const
This is an overloaded member function, provided for convenience. It differs from the above function because it also provides the returned object type in text (char*)
H5G_obj_t getObjTypeByIdx (hsize_t idx, H5std_string &type_name) const
This is an overloaded member function, provided for convenience. It differs from the above function because it also provides the returned object type in text (H5std_string&)
void getObjinfo (const char *name, hbool_t follow_link, H5G_stat_t &statbuf) const
Returns information about an object.
void getObjinfo (const H5std_string &name, hbool_t follow_link, H5G_stat_t &statbuf) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void getObjinfo (const char *name, H5G_stat_t &statbuf) const
This is an overloaded member function, provided for convenience. It differs from the above functions in that it doesn't have the paramemter follow_link.
void getObjinfo (const H5std_string &name, H5G_stat_t &statbuf) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
int iterateElems (const char *name, int *idx, H5G_iterate_t op, void *op_data)
Iterates a user's function over the entries of a group.
int iterateElems (const H5std_string &name, int *idx, H5G_iterate_t op, void *op_data)
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void link (H5L_type_t link_type, const char *curr_name, const char *new_name) const
Creates a link of the specified type from new_name to curr_name.
void link (H5L_type_t link_type, const H5std_string &curr_name, const H5std_string &new_name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for curr_name and new_name.
void unlink (const char *name) const
Removes the specified name at this location.
void unlink (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void mount (const char *name, const H5File &child, const PropList &plist) const
Mounts the file child onto this group.
void mount (const H5std_string &name, const H5File &child, const PropList &plist) const
This is an overloaded member function, provided for convenience. It takes an H5std_string for name.
void unmount (const char *name) const
Unmounts the specified file.
void unmount (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void move (const char *src, const char *dst) const
Renames an object at this location.
void move (const H5std_string &src, const H5std_string &dst) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for src and dst.
virtual void throwException (const H5std_string &func_name, const H5std_string &msg) const
For subclasses, H5File and Group, to throw appropriate exception.
H5Location ()
Public Member Functions inherited from H5::IdComponent
void incRefCount (const hid_t obj_id) const
Increment reference counter for a given id.
void incRefCount () const
Increment reference counter for the id of this object.
void decRefCount (const hid_t obj_id) const
Decrement reference counter for a given id.
void decRefCount () const
Decrement reference counter for the id of this object.
int getCounter (const hid_t obj_id) const
Returns the reference counter for a given id.
int getCounter () const
Returns the reference counter for the id of this object.
H5I_type_t getHDFObjType () const
Returns the type of the object. It is an overloaded function of the above function.
IdComponent & operator= (const IdComponent &rhs)
Assignment operator.
void setId (const hid_t new_id)
Sets the identifier of this object to a new value.
virtual ~IdComponent ()
Noop destructor.
Additional Inherited Members
Static Public Member Functions inherited from H5::IdComponent
static H5I_type_t getHDFObjType (const hid_t obj_id)
Given an id, returns the type of the object.
static hsize_t getNumMembers (H5I_type_t type)
Returns the number of members of the given type.
static bool isValid (hid_t an_id)
Checks if the given ID is valid.
static bool typeExists (H5I_type_t type)
Queries if a given type is currently registered with the library.
Protected Member Functions inherited from H5::H5Location
virtual ~H5Location ()
Member Function Documentation
bool H5::H5Object::attrExists (const char * name) const
Parameters
name - IN: Name of the attribute to be queried
Exceptions
H5::AttributeIException
References getId().
Referenced by attrExists().
bool H5::H5Object::attrExists (const H5std_string & name) const
References attrExists().
Attribute H5::H5Object::createAttribute (const char * name, const DataType & data_type, const DataSpace & data_space, const PropList & create_plist = PropList::DEFAULT) const
Parameters
name - IN: Name of the attribute
data_type - IN: Datatype for the attribute
data_space - IN: Dataspace for the attribute - only simple dataspaces are allowed at this time
create_plist - IN: Creation property list - default to PropList::DEFAULT
Returns
Attribute instance
Exceptions
H5::AttributeIException
Description
The attribute name specified in name must be unique. Attempting to create an attribute with the same name as an existing attribute will raise an exception, leaving the pre-existing attribute intact. To overwrite an existing attribute with a new attribute of the same name, first delete the existing one with H5Object::removeAttr, then recreate it with this function.
References getId(), H5::PropList::getId(), H5::DataSpace::getId(), and H5::DataType::getId().
Referenced by createAttribute().
Attribute H5::H5Object::createAttribute (const H5std_string & name, const DataType & type, const DataSpace & space, const PropList & create_plist = PropList::DEFAULT) const
References createAttribute().
virtual hid_t H5::H5Object::getId () const pure virtual
Implemented in H5::DataType, H5::H5File, H5::DataSet, and H5::Group.
Referenced by attrExists(), createAttribute(), iterateAttrs(), objVersion(), openAttribute(), removeAttr(), and renameAttr().
int H5::H5Object::iterateAttrs (attr_operator_t user_op, unsigned * _idx = NULL, void * op_data = NULL)
Parameters
user_op - IN: User's function to operate on each attribute
_idx - IN/OUT: Starting (IN) and ending (OUT) attribute indices
op_data - IN: User's data to pass to user's operator function
Returns
Returned value of the last operator if it was non-zero, or zero if all attributes were processed
Exceptions
H5::AttributeIException
Description
The signature of user_op is void (*)(H5::H5Location&, H5std_string, void*). For information, please refer to the C layer Reference Manual at: http://www.hdfgroup.org/HDF5/doc/RM/RM_H5A.html#Annot-Iterate
References getId(), H5::UserData4Aiterate::location, H5::UserData4Aiterate::op, and H5::UserData4Aiterate::opData.
unsigned H5::H5Object::objVersion () const
Returns
Object version, which can have the following values:
H5O_VERSION_1
H5O_VERSION_2
Exceptions
H5::ObjHeaderIException Exception will be thrown when:
an error returned by the C API
version number is not one of the valid values above
References getId().
Attribute H5::H5Object::openAttribute (const char * name) const
Parameters
name - IN: Name of the attribute
Returns
Attribute instance
Exceptions
H5::AttributeIException
References getId().
Referenced by openAttribute().
Attribute H5::H5Object::openAttribute (const H5std_string & name) const
References openAttribute().
Attribute H5::H5Object::openAttribute (const unsigned int idx) const
Parameters
idx - IN: Index of the attribute, a 0-based, non-negative integer
Returns
Attribute instance
Exceptions
H5::AttributeIException
References getId().
void H5::H5Object::removeAttr (const char * name) const
Parameters
name - IN: Name of the attribute to be removed
Exceptions
H5::AttributeIException
References getId().
Referenced by removeAttr().
void H5::H5Object::removeAttr (const H5std_string & name) const
References removeAttr().
void H5::H5Object::renameAttr (const char * oldname, const char * newname) const
Parameters
oldname - IN: Name of the attribute to be renamed
newname - IN: New name ame of the attribute
Exceptions
H5::AttributeIException
References getId().
Referenced by renameAttr().
void H5::H5Object::renameAttr (const H5std_string & oldname, const H5std_string & newname) const
References renameAttr().
The documentation for this class was generated from the following files:
H5Object.h
H5Object.cpp
The HDF Group Help Desk:
Copyright by The HDF Group
and the Board of Trustees of the University of Illinois