My Project: H5::Attribute Class Reference
H5::Attribute Class Reference
Class Attribute operates on HDF5 attributes.
#include <H5Attribute.h>
Public Member Functions
Attribute (const Attribute &original)
Copy constructor: same HDF5 object as original.
Attribute ()
Default constructor: Creates a stub attribute.
Attribute (const hid_t attr_id)
Creates an Attribute object using the id of an existing attribute.
virtual void close ()
Closes this attribute.
ssize_t getName (char *attr_name, size_t buf_size=0) const
Gets the name of this attribute, returning its length.
H5std_string getName (size_t len) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an integer specifying a desired length to be retrieved of the name.
H5std_string getName () const
Returns the name of this attribute as an H5std_string.
ssize_t getName (H5std_string &attr_name, size_t len=0) const
Gets the name of this attribute, returning its length.
ssize_t getName (size_t buf_size, H5std_string &attr_name) const
virtual DataSpace getSpace () const
Gets a copy of the dataspace for this attribute.
virtual hsize_t getStorageSize () const
Returns the amount of storage size required for this attribute.
virtual size_t getInMemDataSize () const
Gets the size in memory of the attribute's data.
void read (const DataType &mem_type, void *buf) const
Reads data from this attribute.
void read (const DataType &mem_type, H5std_string &strg) const
This is an overloaded member function, provided for convenience. It reads a H5std_string from this attribute.
void write (const DataType &mem_type, const void *buf) const
Writes data to this attribute.
void write (const DataType &mem_type, const H5std_string &strg) const
This is an overloaded member function, provided for convenience. It writes a H5std_string to this attribute.
virtual H5std_string fromClass () const
Returns this class name.
virtual hid_t getId () const
Get the id of this attribute.
virtual ~Attribute ()
Properly terminates access to this attribute.
Public Member Functions inherited from H5::AbstractDs
DataType getDataType () const
Returns the generic datatype of this abstract dataset, which can be a dataset or an attribute.
ArrayType getArrayType () const
Returns the array datatype of this abstract dataset which can be a dataset or an attribute.
CompType getCompType () const
Returns the compound datatype of this abstract dataset which can be a dataset or an attribute.
EnumType getEnumType () const
Returns the enumeration datatype of this abstract dataset which can be a dataset or an attribute.
IntType getIntType () const
Returns the integer datatype of this abstract dataset which can be a dataset or an attribute.
FloatType getFloatType () const
Returns the floating-point datatype of this abstract dataset, which can be a dataset or an attribute.
StrType getStrType () const
Returns the string datatype of this abstract dataset which can be a dataset or an attribute.
VarLenType getVarLenType () const
Returns the floating-point datatype of this abstract dataset, which can be a dataset or an attribute.
H5T_class_t getTypeClass () const
Creates an AbstractDs instance using an existing id.
virtual ~AbstractDs ()
Noop destructor.
Public Member Functions inherited from H5::H5Location
bool nameExists (const char *name, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Checks if a link of a given name exists in a location.
bool nameExists (const H5std_string &name, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Checks if a link of a given name exists in a location.
bool exists (const char *name, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Deprecated in favor of nameExists.
bool exists (const H5std_string &name, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Deprecated in favor of nameExists.
void flush (H5F_scope_t scope) const
Flushes all buffers associated with a location to disk.
H5std_string getFileName () const
Gets the name of the file, in which an HDF5 object at this location belongs.
H5G_obj_t getObjType (void *ref, H5R_type_t ref_type=H5R_OBJECT) const
Retrieves the type of object that an object reference points to.
H5O_type_t getRefObjType (void *ref, H5R_type_t ref_type=H5R_OBJECT) const
Retrieves the type of object that an object reference points to.
void setComment (const char *name, const char *comment) const
Sets or resets the comment for an object specified by its name.
void setComment (const H5std_string &name, const H5std_string &comment) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name and comment.
void setComment (const char *comment) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it doesn't take an object name.
void setComment (const H5std_string &comment) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for comment.
ssize_t getComment (const char *name, size_t buf_size, char *comment) const
Retrieves the comment for this location, returning its length.
H5std_string getComment (const char *name, size_t buf_size=0) const
Returns the comment as string for this location, returning its length.
H5std_string getComment (const H5std_string &name, size_t buf_size=0) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void removeComment (const char *name) const
Removes the comment from an object specified by its name.
void removeComment (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void reference (void *ref, const char *name, H5R_type_t ref_type=H5R_OBJECT) const
This is an overloaded function, provided for your convenience. It differs from the above function in that it does not take a DataSpace object and the reference type must be specified.
void reference (void *ref, const H5std_string &name, H5R_type_t ref_type=H5R_OBJECT) const
This is an overloaded function, provided for your convenience. It differs from the above function in that it takes an H5std_string for the object's name.
void reference (void *ref, const char *name, const DataSpace &dataspace, H5R_type_t ref_type=H5R_DATASET_REGION) const
Creates a reference to an HDF5 object or a dataset region.
void reference (void *ref, const H5std_string &name, const DataSpace &dataspace, H5R_type_t ref_type=H5R_DATASET_REGION) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void dereference (const H5Location &loc, const void *ref, H5R_type_t ref_type=H5R_OBJECT, const PropList &plist=PropList::DEFAULT)
Dereferences a reference into an HDF5 object, given an HDF5 object.
DataSpace getRegion (void *ref, H5R_type_t ref_type=H5R_DATASET_REGION) const
Retrieves a dataspace with the region pointed to selected.
Group createGroup (const char *name, const LinkCreatPropList &lcpl) const
Creates a new group at this location, which can be a file, group, dataset, attribute, or named datatype.
Group createGroup (const H5std_string &name, const LinkCreatPropList &lcpl) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
Group createGroup (const char *name, size_t size_hint=0) const
Creates a new group at this location, which can be a file, group, dataset, attribute, or named datatype.
Group createGroup (const H5std_string &name, size_t size_hint=0) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
Group openGroup (const char *name) const
Opens an existing group in a location which can be a file or another group.
Group openGroup (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
DataSet createDataSet (const char *name, const DataType &data_type, const DataSpace &data_space, const DSetCreatPropList &create_plist=DSetCreatPropList::DEFAULT, const DSetAccPropList &dapl=DSetAccPropList::DEFAULT, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT) const
Creates a new dataset at this location.
DataSet createDataSet (const H5std_string &name, const DataType &data_type, const DataSpace &data_space, const DSetCreatPropList &create_plist=DSetCreatPropList::DEFAULT, const DSetAccPropList &dapl=DSetAccPropList::DEFAULT, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
DataSet openDataSet (const char *name, const DSetAccPropList &dapl=DSetAccPropList::DEFAULT) const
Opens an existing dataset at this location.
DataSet openDataSet (const H5std_string &name, const DSetAccPropList &dapl=DSetAccPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
H5L_info2_t getLinkInfo (const char *link_name, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Returns the information of the named link.
H5L_info2_t getLinkInfo (const H5std_string &link_name, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for link_name.
H5std_string getLinkval (const char *link_name, size_t size=0) const
Returns the name of the object that the symbolic link points to.
H5std_string getLinkval (const H5std_string &link_name, size_t size=0) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
hsize_t getNumObjs () const
Deprecated - moved to H5::Group in 1.10.2.
H5std_string getObjnameByIdx (hsize_t idx) const
Returns the name of an object in this group, given the object's index.
ssize_t getObjnameByIdx (hsize_t idx, char *name, size_t size) const
Retrieves the name of an object in this group, given the object's index.
ssize_t getObjnameByIdx (hsize_t idx, H5std_string &name, size_t size) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
H5O_type_t childObjType (const H5std_string &objname) const
This is an overloaded member function, provided for convenience. It takes an H5std_string for the object's name.
H5O_type_t childObjType (const char *objname) const
Returns the type of an object in this file/group, given the object's name.
H5O_type_t childObjType (hsize_t index, H5_index_t index_type=H5_INDEX_NAME, H5_iter_order_t order=H5_ITER_INC, const char *objname=".") const
Returns the type of an object in this file/group, given the object's index and its type and order.
unsigned childObjVersion (const char *objname) const
Returns the object header version of an object in this file/group, given the object's name.
unsigned childObjVersion (const H5std_string &objname) const
This is an overloaded member function, provided for convenience. It takes an H5std_string for the object's name.
void getObjinfo (H5O_info2_t &objinfo, unsigned fields=H5O_INFO_BASIC) const
Retrieves information about an HDF5 object.
void getObjinfo (const char *name, H5O_info2_t &objinfo, unsigned fields=H5O_INFO_BASIC, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Retrieves information about an HDF5 object given its name.
void getObjinfo (const H5std_string &name, H5O_info2_t &objinfo, unsigned fields=H5O_INFO_BASIC, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for name.
void getObjinfo (const char *grp_name, H5_index_t idx_type, H5_iter_order_t order, hsize_t idx, H5O_info2_t &objinfo, unsigned fields=H5O_INFO_BASIC, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Retrieves information about an HDF5 object given its index.
void getObjinfo (const H5std_string &grp_name, H5_index_t idx_type, H5_iter_order_t order, hsize_t idx, H5O_info2_t &objinfo, unsigned fields=H5O_INFO_BASIC, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for name.
void getNativeObjinfo (H5O_native_info_t &objinfo, unsigned fields=H5O_NATIVE_INFO_HDR) const
Retrieves native information about an HDF5 object.
void getNativeObjinfo (const char *name, H5O_native_info_t &objinfo, unsigned fields=H5O_NATIVE_INFO_HDR, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Retrieves native information about an HDF5 object given its name.
void getNativeObjinfo (const H5std_string &name, H5O_native_info_t &objinfo, unsigned fields=H5O_NATIVE_INFO_HDR, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for name.
void getNativeObjinfo (const char *grp_name, H5_index_t idx_type, H5_iter_order_t order, hsize_t idx, H5O_native_info_t &objinfo, unsigned fields=H5O_NATIVE_INFO_HDR, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Retrieves native information about an HDF5 object given its index.
void getNativeObjinfo (const H5std_string &grp_name, H5_index_t idx_type, H5_iter_order_t order, hsize_t idx, H5O_native_info_t &objinfo, unsigned fields=H5O_NATIVE_INFO_HDR, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for name.
H5G_obj_t getObjTypeByIdx (hsize_t idx) const
Returns the type of an object in this group, given the object's index.
H5G_obj_t getObjTypeByIdx (hsize_t idx, char *type_name) const
This is an overloaded member function, provided for convenience. It differs from the above function because it also provides the returned object type in text (char*)
H5G_obj_t getObjTypeByIdx (hsize_t idx, H5std_string &type_name) const
This is an overloaded member function, provided for convenience. It differs from the above function because it also provides the returned object type in text (H5std_string&)
void getObjinfo (const char *name, hbool_t follow_link, H5G_stat_t &statbuf) const
Returns information about an object.
void getObjinfo (const H5std_string &name, hbool_t follow_link, H5G_stat_t &statbuf) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void getObjinfo (const char *name, H5G_stat_t &statbuf) const
This is an overloaded member function, provided for convenience. It differs from the above functions in that it doesn't have the paramemter follow_link.
void getObjinfo (const H5std_string &name, H5G_stat_t &statbuf) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
int iterateElems (const char *name, int *idx, H5G_iterate_t op, void *op_data)
Iterates a user's function over the entries of a group.
int iterateElems (const H5std_string &name, int *idx, H5G_iterate_t op, void *op_data)
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void link (const char *target_name, const char *link_name, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Creates a soft link from link_name to target_name.
void link (const H5std_string &target_name, const H5std_string &link_name, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for target_name and link_name.
void link (const char *curr_name, const Group &new_loc, const char *new_name, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Creates a hard link from new_name to curr_name.
void link (const H5std_string &curr_name, const Group &new_loc, const H5std_string &new_name, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for curr_name and new_name.
void link (const char *curr_name, const hid_t same_loc, const char *new_name, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Creates a hard link from new_name to curr_name - can be used to pass in H5L_SAME_LOC.
void link (const H5std_string &curr_name, const hid_t same_loc, const H5std_string &new_name, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for curr_name and new_name.
void link (H5L_type_t link_type, const char *curr_name, const char *new_name) const
Creates a link of the specified type from new_name to curr_name.
void link (H5L_type_t link_type, const H5std_string &curr_name, const H5std_string &new_name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for curr_name and new_name.
void unlink (const char *link_name, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Removes the specified link from this group.
void unlink (const H5std_string &link_name, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void mount (const char *name, const H5File &child, const PropList &plist) const
Mounts the file child onto this group.
void mount (const H5std_string &name, const H5File &child, const PropList &plist) const
This is an overloaded member function, provided for convenience. It takes an H5std_string for name.
void unmount (const char *name) const
Unmounts the specified file.
void unmount (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void copyLink (const char *src_name, const Group &dst, const char *dst_name, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Copies a link from one group to another.
void copyLink (const H5std_string &src_name, const Group &dst, const H5std_string &dst_name, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for src_name and dst_name.
void copyLink (const char *src_name, const char *dst_name, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Copies a link from a group in the same location.
void copyLink (const H5std_string &src_name, const H5std_string &dst_name, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for src_name and dst_name.
void moveLink (const char *src_name, const Group &dst, const char *dst_name, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Renames a link in this group and moves it to a new location.
void moveLink (const H5std_string &src_name, const Group &dst, const H5std_string &dst_name, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for src_name and dst_name.
void moveLink (const char *src_name, const char *dst_name, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
Renames a link in this group.
void moveLink (const H5std_string &src_name, const H5std_string &dst_name, const LinkCreatPropList &lcpl=LinkCreatPropList::DEFAULT, const LinkAccPropList &lapl=LinkAccPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for src_name and dst_name.
void move (const char *src, const char *dst) const
Renames an object at this location. - Deprecated due to inadequate functionality.
void move (const H5std_string &src, const H5std_string &dst) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for src and dst. - Deprecated due to inadequate functionality.
virtual void throwException (const H5std_string &func_name, const H5std_string &msg) const
For subclasses, H5File and Group, to throw appropriate exception.
H5Location ()
Public Member Functions inherited from H5::IdComponent
void incRefCount (const hid_t obj_id) const
Increment reference counter for a given id.
void incRefCount () const
Increment reference counter for the id of this object.
void decRefCount (const hid_t obj_id) const
Decrement reference counter for a given id.
void decRefCount () const
Decrement reference counter for the id of this object.
int getCounter (const hid_t obj_id) const
Returns the reference counter for a given id.
int getCounter () const
Returns the reference counter for the id of this object.
H5I_type_t getHDFObjType () const
Returns the type of the object. It is an overloaded function of the above function.
IdComponent & operator= (const IdComponent &rhs)
Assignment operator.
void setId (const hid_t new_id)
Sets the identifier of this object to a new value.
virtual ~IdComponent ()
Noop destructor.
Friends
void f_Attribute_setId (Attribute *attr, hid_t new_id)
Additional Inherited Members
Static Public Member Functions inherited from H5::IdComponent
static H5I_type_t getHDFObjType (const hid_t obj_id)
Given an id, returns the type of the object.
static hsize_t getNumMembers (H5I_type_t type)
Returns the number of members of the given type.
static bool isValid (hid_t an_id)
Checks if the given ID is valid.
static bool typeExists (H5I_type_t type)
Queries if a given type is currently registered with the library.
Protected Member Functions inherited from H5::AbstractDs
AbstractDs ()
Default constructor.
Protected Member Functions inherited from H5::H5Location
virtual ~H5Location ()
Noop destructor.
Detailed Description
An attribute has many characteristics similar to a dataset, thus both Attribute and DataSet are derivatives of AbstractDs. Attribute also inherits from H5Location because an attribute can be used to specify a location.
Constructor & Destructor Documentation
Attribute() [1/3]
H5::Attribute::Attribute (const Attribute & original)
Parameters
original - IN: Original Attribute object to copy
References H5::IdComponent::incRefCount().
Attribute() [2/3]
H5::Attribute::Attribute ()
Attribute() [3/3]
H5::Attribute::Attribute (const hid_t existing_id)
Parameters
existing_id - IN: Id of an existing attribute
Exceptions
H5::AttributeIException
References H5::IdComponent::incRefCount().
~Attribute()
H5::Attribute::~Attribute () virtual
References close(), and H5::Exception::getDetailMsg().
Member Function Documentation
close()
void H5::Attribute::close () virtual
Exceptions
H5::AttributeIException
Referenced by ~Attribute().
fromClass()
virtual H5std_string H5::Attribute::fromClass () const inline virtual
Implements H5::AbstractDs.
getId()
hid_t H5::Attribute::getId () const virtual
Returns
Attribute identifier
Referenced by H5::DataSet::DataSet().
getInMemDataSize()
size_t H5::Attribute::getInMemDataSize () const virtual
Returns
Size of data (in memory)
Exceptions
H5::AttributeIException
Implements H5::AbstractDs.
getName() [1/5]
H5std_string H5::Attribute::getName () const
Returns
Name of the attribute
Exceptions
H5::AttributeIException
Referenced by getName().
getName() [2/5]
ssize_t H5::Attribute::getName (char * attr_name, size_t buf_size = 0) const
Parameters
attr_name - OUT: Buffer for the name string as char*
buf_size - IN: Length of the buffer, default to 0
Returns
Actual length of the attribute name
Exceptions
H5::AttributeIException
Description
This function retrieves buf_size chars of the attribute's name including null termination. Thus, if the actual length of the name is more than buf_size-1, the retrieved name will be truncated to accommodate the null terminator. To get length of the attribute's name for buffer allocation, an application can call this function passing in NULL for the first argument and ignore the second argument.
getName() [3/5]
ssize_t H5::Attribute::getName (H5std_string & attr_name, size_t len = 0) const
Parameters
attr_name - OUT: Buffer for the name string as H5std_string
len - IN: Desired length of the name, default to 0
Returns
Actual length of the attribute name
Exceptions
H5::AttributeIException
Description
This function retrieves the attribute's name as a string. The buf_size can specify a specific length or default to 0, in which case the entire name will be retrieved.
References getName().
getName() [4/5]
ssize_t H5::Attribute::getName (size_t buf_size, H5std_string & attr_name) const
getName() [5/5]
H5std_string H5::Attribute::getName (size_t len) const
Returns
Name (or part of name) of the attribute
Parameters
len - IN: Desired length of the name
Exceptions
H5::AttributeIException
References getName().
getSpace()
DataSpace H5::Attribute::getSpace () const virtual
Returns
Dataspace instance
Exceptions
H5::AttributeIException
Implements H5::AbstractDs.
References H5::f_DataSpace_setId().
getStorageSize()
hsize_t H5::Attribute::getStorageSize () const virtual
Returns
Size of the storage or 0, for no data
Exceptions
H5::AttributeIException
Implements H5::AbstractDs.
read() [1/2]
void H5::Attribute::read (const DataType & mem_type, H5std_string & strg) const
Parameters
mem_type - IN: Attribute datatype (in memory)
strg - IN: Buffer for read string
Exceptions
H5::AttributeIException
References H5::DataType::getId().
read() [2/2]
void H5::Attribute::read (const DataType & mem_type, void * buf) const
Parameters
mem_type - IN: Attribute datatype (in memory)
buf - OUT: Buffer for read data
Exceptions
H5::AttributeIException
References H5::DataType::getId().
write() [1/2]
void H5::Attribute::write (const DataType & mem_type, const H5std_string & strg) const
Parameters
mem_type - IN: Attribute datatype (in memory)
strg - IN: Data to be written
Exceptions
H5::AttributeIException
References H5::DataType::getId().
write() [2/2]
void H5::Attribute::write (const DataType & mem_type, const void * buf) const
Parameters
mem_type - IN: Attribute datatype (in memory)
buf - IN: Data to be written
Exceptions
H5::AttributeIException
References H5::DataType::getId().
Friends And Related Function Documentation
f_Attribute_setId
void f_Attribute_setId (Attribute * attr, hid_t new_id) friend
The documentation for this class was generated from the following files:
H5Attribute.h
H5Attribute.cpp
The HDF Group Help Desk:
Copyright by The HDF Group
and the Board of Trustees of the University of Illinois