My Project: H5::DataSpace Class Reference
H5::DataSpace Class Reference
Class DataSpace inherits from IdComponent and provides wrappers for the HDF5's dataspaces.
#include <H5DataSpace.h>
Public Member Functions
DataSpace (H5S_class_t type=H5S_SCALAR)
Creates a new dataspace given a dataspace type.
DataSpace (int rank, const hsize_t *dims, const hsize_t *maxdims=NULL)
Creates a new simple dataspace.
DataSpace (const hid_t space_id)
Creates a DataSpace object using the id of an existing dataspace.
DataSpace (const DataSpace &original)
Copy constructor: same HDF5 object as original.
DataSpace & operator= (const DataSpace &rhs)
Assignment operator.
virtual void close () H5_OVERRIDE
Closes this dataspace.
void copy (const DataSpace &like_space)
Makes a copy of an existing dataspace.
void extentCopy (const DataSpace &dest_space) const
Copies the extent of a dataspace.
void getSelectBounds (hsize_t *start, hsize_t *end) const
Gets the bounding box containing the current selection.
hssize_t getSelectElemNpoints () const
Returns the number of element points in the current selection.
void getSelectElemPointlist (hsize_t startpoint, hsize_t numpoints, hsize_t *buf) const
Gets the list of element points currently selected.
void getSelectHyperBlocklist (hsize_t startblock, hsize_t numblocks, hsize_t *buf) const
Gets the list of hyperslab blocks currently selected.
hssize_t getSelectHyperNblocks () const
Returns number of hyperslab blocks.
hssize_t getSelectNpoints () const
Returns the number of elements in a dataspace selection.
int getSimpleExtentDims (hsize_t *dims, hsize_t *maxdims=NULL) const
Retrieves dataspace dimension size and maximum size.
int getSimpleExtentNdims () const
Returns the dimensionality of a dataspace.
hssize_t getSimpleExtentNpoints () const
Returns the number of elements in a dataspace.
H5S_class_t getSimpleExtentType () const
Returns the current class of a dataspace.
bool isSimple () const
Determines whether this dataspace is a simple dataspace.
void offsetSimple (const hssize_t *offset) const
Sets the offset of this simple dataspace.
void selectAll () const
Selects the entire dataspace.
void selectElements (H5S_seloper_t op, const size_t num_elements, const hsize_t *coord) const
Selects array elements to be included in the selection for this dataspace.
void selectHyperslab (H5S_seloper_t op, const hsize_t *count, const hsize_t *start, const hsize_t *stride=NULL, const hsize_t *block=NULL) const
Selects a hyperslab region to add to the current selected region.
void selectNone () const
Resets the selection region to include no elements.
bool selectValid () const
Verifies that the selection is within the extent of the dataspace.
void setExtentNone () const
Removes the extent from a dataspace.
void setExtentSimple (int rank, const hsize_t *current_size, const hsize_t *maximum_size=NULL) const
Sets or resets the size of an existing dataspace.
virtual H5std_string fromClass () const H5_OVERRIDE
Returns this class name.
virtual hid_t getId () const H5_OVERRIDE
Get the id of this dataspace.
virtual ~DataSpace ()
Properly terminates access to this dataspace.
Public Member Functions inherited from H5::IdComponent
void incRefCount (const hid_t obj_id) const
Increment reference counter for a given id.
void incRefCount () const
Increment reference counter for the id of this object.
void decRefCount (const hid_t obj_id) const
Decrement reference counter for a given id.
void decRefCount () const
Decrement reference counter for the id of this object.
int getCounter (const hid_t obj_id) const
Returns the reference counter for a given id.
int getCounter () const
Returns the reference counter for the id of this object.
H5I_type_t getHDFObjType () const
Returns the type of the object. It is an overloaded function of the above function.
IdComponent & operator= (const IdComponent &rhs)
Assignment operator.
void setId (const hid_t new_id)
Sets the identifier of this object to a new value.
virtual ~IdComponent ()
Noop destructor.
Static Public Member Functions
static void deleteConstants ()
Static Public Member Functions inherited from H5::IdComponent
static H5I_type_t getHDFObjType (const hid_t obj_id)
Given an id, returns the type of the object.
static hsize_t getNumMembers (H5I_type_t type)
Returns the number of members of the given type.
static bool isValid (hid_t an_id)
Checks if the given ID is valid.
static bool typeExists (H5I_type_t type)
Queries if a given type is currently registered with the library.
Static Public Attributes
static const DataSpace & ALL
Default DataSpace objects.
Detailed Description
Examples
chunks.cpp, compound.cpp, create.cpp, extend_ds.cpp, h5group.cpp, readdata.cpp, and writedata.cpp.
Constructor & Destructor Documentation
DataSpace() [1/4]
H5::DataSpace::DataSpace (H5S_class_t type = H5S_SCALAR)
Parameters
type - IN: Type of the dataspace to be created, which currently can be either H5S_SCALAR or H5S_SIMPLE; default to H5S_SCALAR.
Exceptions
H5::DataSpaceIException
DataSpace() [2/4]
H5::DataSpace::DataSpace (int rank, const hsize_t * dims, const hsize_t * maxdims = NULL)
Parameters
rank - IN: Number of dimensions of dataspace.
dims - IN: An array of the size of each dimension.
maxdims - IN: An array of the maximum size of each dimension.
Exceptions
H5::DataSpaceIException
DataSpace() [3/4]
H5::DataSpace::DataSpace (const hid_t existing_id)
Parameters
existing_id - IN: Id of an existing dataspace
Exceptions
H5::DataSpaceIException
References H5::IdComponent::incRefCount().
DataSpace() [4/4]
H5::DataSpace::DataSpace (const DataSpace & original)
Parameters
original - IN: DataSpace object to copy
References H5::IdComponent::incRefCount().
~DataSpace()
H5::DataSpace::~DataSpace () virtual
References close(), and H5::Exception::getDetailMsg().
Member Function Documentation
close()
void H5::DataSpace::close () virtual
Exceptions
H5::DataSpaceIException
Referenced by copy(), and ~DataSpace().
copy()
void H5::DataSpace::copy (const DataSpace & like_space)
Parameters
like_space - IN: Dataspace to be copied
Exceptions
H5::DataSpaceIException
References close(), H5::Exception::getDetailMsg(), and getId().
Referenced by operator=().
deleteConstants()
static void H5::DataSpace::deleteConstants () static
Referenced by H5::H5Library::initH5cpp().
extentCopy()
void H5::DataSpace::extentCopy (const DataSpace & dest_space) const
Parameters
dest_space - IN: Dataspace to copy from
Exceptions
H5::DataSpaceIException
References getId().
fromClass()
virtual H5std_string H5::DataSpace::fromClass () const inline virtual
getId()
hid_t H5::DataSpace::getId () const virtual
Returns
Dataspace identifier
Referenced by copy(), H5::H5Object::createAttribute(), H5::H5Location::createDataSet(), extentCopy(), H5::DataSet::fillMemBuf(), H5::DataSet::getVlenBufSize(), H5::DataSet::iterateElems(), H5::DataSet::read(), H5::H5Location::reference(), H5::DSetCreatPropList::setVirtual(), H5::DataSet::vlenReclaim(), and H5::DataSet::write().
getSelectBounds()
void H5::DataSpace::getSelectBounds (hsize_t * start, hsize_t * end) const
Parameters
start - IN: Starting coordinates of the bounding box
end - IN: Ending coordinates of the bounding box, i.e., the coordinates of the diagonally opposite corner
Exceptions
H5::DataSpaceIException
Description
For information, please refer to the H5Sget_select_bounds API in the HDF5 C Reference Manual.
getSelectElemNpoints()
hssize_t H5::DataSpace::getSelectElemNpoints () const
Returns
Number of element points
Exceptions
H5::DataSpaceIException
getSelectElemPointlist()
void H5::DataSpace::getSelectElemPointlist (hsize_t startpoint, hsize_t numpoints, hsize_t * buf) const
Parameters
startpoint - IN: Element point to start with
numpoints - IN: Number of element points to get
buf - IN: List of element points selected
Exceptions
H5::DataSpaceIException
Description
For information, please refer to the C API H5Sget_select_elem_pointlist in the HDF5 C Reference Manual.
getSelectHyperBlocklist()
void H5::DataSpace::getSelectHyperBlocklist (hsize_t startblock, hsize_t numblocks, hsize_t * buf) const
Parameters
startblock - IN: Hyperslab block to start with
numblocks - IN: Number of hyperslab blocks to get
buf - IN: List of hyperslab blocks selected
Exceptions
H5::DataSpaceIException
getSelectHyperNblocks()
hssize_t H5::DataSpace::getSelectHyperNblocks () const
Returns
Number of hyperslab blocks
Exceptions
H5::DataSpaceIException
getSelectNpoints()
hssize_t H5::DataSpace::getSelectNpoints () const
Returns
Number of elements
Exceptions
H5::DataSpaceIException
getSimpleExtentDims()
int H5::DataSpace::getSimpleExtentDims (hsize_t * dims, hsize_t * maxdims = NULL) const
Parameters
dims - IN: Name of the new member
maxdims - IN: Pointer to the value of the new member
Returns
Number of dimensions, the same value as returned by DataSpace::getSimpleExtentNdims()
Exceptions
H5::DataSpaceIException
Examples
chunks.cpp, and readdata.cpp.
getSimpleExtentNdims()
int H5::DataSpace::getSimpleExtentNdims () const
Returns
Number of dimensions
Exceptions
H5::DataSpaceIException
Examples
chunks.cpp, and readdata.cpp.
getSimpleExtentNpoints()
hssize_t H5::DataSpace::getSimpleExtentNpoints () const
Returns
Number of elements
Exceptions
H5::DataSpaceIException
getSimpleExtentType()
H5S_class_t H5::DataSpace::getSimpleExtentType () const
Returns
Class of the dataspace
Exceptions
H5::DataSpaceIException
isSimple()
bool H5::DataSpace::isSimple () const
Returns
true if the dataspace is a simple dataspace, and false, otherwise
Exceptions
H5::DataSpaceIException
offsetSimple()
void H5::DataSpace::offsetSimple (const hssize_t * offset) const
Parameters
offset - IN: Offset to position the selection at
Exceptions
H5::DataSpaceIException
Description
This function creates an offset for the selection within an extent, allowing the same shaped selection to be moved to different locations within a dataspace without requiring it to be re-defined.
operator=()
DataSpace & H5::DataSpace::operator= (const DataSpace & rhs)
Parameters
rhs - IN: Reference to the existing dataspace
Returns
Reference to DataSpace instance
Exceptions
H5::DataSpaceIException
References copy().
selectAll()
void H5::DataSpace::selectAll () const
Exceptions
H5::DataSpaceIException
selectElements()
void H5::DataSpace::selectElements (H5S_seloper_t op, const size_t num_elements, const hsize_t * coord) const
Parameters
op - IN: Operator specifying how the new selection is to be combined with the existing selection for the dataspace
num_elements - IN: Number of elements to be selected
coord - IN: A 2-dimensional array of 0-based values specifying the coordinates of the elements being selected
Exceptions
H5::DataSpaceIException
Description
For information, please refer to the H5Sselect_elements API in the HDF5 C Reference Manual.
selectHyperslab()
void H5::DataSpace::selectHyperslab (H5S_seloper_t op, const hsize_t * count, const hsize_t * start, const hsize_t * stride = NULL, const hsize_t * block = NULL) const
Parameters
op - IN: Operation to perform on current selection
count - IN: Number of blocks included in the hyperslab
start - IN: Offset of the start of hyperslab
stride - IN: Hyperslab stride - default to NULL
block - IN: Size of block in the hyperslab - default to NULL
Exceptions
H5::DataSpaceIException
Description
For information, please refer to the H5Sselect_hyperslab API in the HDF5 C Reference Manual.
Examples
chunks.cpp, extend_ds.cpp, readdata.cpp, and writedata.cpp.
selectNone()
void H5::DataSpace::selectNone () const
Exceptions
H5::DataSpaceIException
selectValid()
bool H5::DataSpace::selectValid () const
Returns
true if the selection is within the extent of the dataspace, and false, otherwise
Exceptions
H5::DataSpaceIException
setExtentNone()
void H5::DataSpace::setExtentNone () const
Exceptions
H5::DataSpaceIException
setExtentSimple()
void H5::DataSpace::setExtentSimple (int rank, const hsize_t * current_size, const hsize_t * maximum_size = NULL) const
Parameters
rank - IN: Rank of the dataspace
current_size - IN: Array containing current size of dataspace
maximum_size - IN: Array containing maximum size of dataspace
Exceptions
H5::DataSpaceIException
Member Data Documentation
ALL
const DataSpace& H5::DataSpace::ALL static
The documentation for this class was generated from the following files:
H5DataSpace.h
H5DataSpace.cpp
The HDF Group Help Desk:
Copyright by The HDF Group
and the Board of Trustees of the University of Illinois