My Project: H5::AbstractDs Class Reference
H5::AbstractDs Class Reference abstract
AbstractDs is an abstract base class, inherited by Attribute and DataSet.
#include <H5AbstractDs.h>
Public Member Functions
DataType getDataType () const
Returns the generic datatype of this abstract dataset, which can be a dataset or an attribute.
ArrayType getArrayType () const
Returns the array datatype of this abstract dataset which can be a dataset or an attribute.
CompType getCompType () const
Returns the compound datatype of this abstract dataset which can be a dataset or an attribute.
EnumType getEnumType () const
Returns the enumeration datatype of this abstract dataset which can be a dataset or an attribute.
IntType getIntType () const
Returns the integer datatype of this abstract dataset which can be a dataset or an attribute.
FloatType getFloatType () const
Returns the floating-point datatype of this abstract dataset, which can be a dataset or an attribute.
StrType getStrType () const
Returns the string datatype of this abstract dataset which can be a dataset or an attribute.
VarLenType getVarLenType () const
Returns the floating-point datatype of this abstract dataset, which can be a dataset or an attribute.
virtual size_t getInMemDataSize () const =0
Gets the size in memory of this abstract dataset.
virtual DataSpace getSpace () const =0
Gets the dataspace of this abstract dataset - pure virtual.
H5T_class_t getTypeClass () const
Creates an AbstractDs instance using an existing id.
virtual hsize_t getStorageSize () const =0
Returns the amount of storage size required - pure virtual.
virtual H5std_string fromClass () const =0
virtual ~AbstractDs ()
Noop destructor.
Protected Member Functions
AbstractDs ()
Default constructor.
Detailed Description
It provides a collection of services that are common to both Attribute and DataSet.
Constructor & Destructor Documentation
~AbstractDs()
H5::AbstractDs::~AbstractDs () virtual
AbstractDs()
H5::AbstractDs::AbstractDs () protected
Member Function Documentation
fromClass()
virtual H5std_string H5::AbstractDs::fromClass () const pure virtual
Implemented in H5::DataSet, and H5::Attribute.
Referenced by getTypeClass().
getArrayType()
ArrayType H5::AbstractDs::getArrayType () const
Returns
ArrayType instance
Exceptions
H5::DataTypeIException
References H5::Exception::getDetailMsg().
getCompType()
CompType H5::AbstractDs::getCompType () const
Returns
CompType instance
Exceptions
H5::DataTypeIException
References H5::Exception::getDetailMsg().
getDataType()
DataType H5::AbstractDs::getDataType () const
Returns
DataType instance
Exceptions
H5::DataTypeIException
References H5::Exception::getDetailMsg().
getEnumType()
EnumType H5::AbstractDs::getEnumType () const
Returns
EnumType instance
Exceptions
H5::DataTypeIException
References H5::Exception::getDetailMsg().
getFloatType()
FloatType H5::AbstractDs::getFloatType () const
Returns
FloatType instance
Exceptions
H5::DataTypeIException
References H5::Exception::getDetailMsg().
getInMemDataSize()
virtual size_t H5::AbstractDs::getInMemDataSize () const pure virtual
Implemented in H5::DataSet, and H5::Attribute.
getIntType()
IntType H5::AbstractDs::getIntType () const
Returns
IntType instance
Exceptions
H5::DataTypeIException
Examples
readdata.cpp.
References H5::Exception::getDetailMsg().
getSpace()
virtual DataSpace H5::AbstractDs::getSpace () const pure virtual
Implemented in H5::DataSet, and H5::Attribute.
getStorageSize()
virtual hsize_t H5::AbstractDs::getStorageSize () const pure virtual
Implemented in H5::DataSet, and H5::Attribute.
getStrType()
StrType H5::AbstractDs::getStrType () const
Returns
StrType instance
Exceptions
H5::DataTypeIException
References H5::Exception::getDetailMsg().
getTypeClass()
H5T_class_t H5::AbstractDs::getTypeClass () const
Returns the class of the datatype that is used by this object, which can be a dataset or an attribute.
Returns
Datatype class identifier
Exceptions
H5::DataTypeIException
Examples
readdata.cpp.
References fromClass(), and H5::Exception::getDetailMsg().
getVarLenType()
VarLenType H5::AbstractDs::getVarLenType () const
Returns
VarLenType instance
Exceptions
H5::DataTypeIException
References H5::Exception::getDetailMsg().
The documentation for this class was generated from the following files:
H5AbstractDs.h
H5AbstractDs.cpp
The HDF Group Help Desk:
Copyright by The HDF Group
and the Board of Trustees of the University of Illinois