My Project: H5 Namespace Reference
H5 Namespace Reference
Classes
class AbstractDs
AbstractDs is an abstract base class, inherited by Attribute and DataSet.
class ArrayType
Class ArrayType inherits from DataType and provides wrappers for the HDF5's Array Datatypes.
class AtomType
AtomType is a base class, inherited by IntType, FloatType, StrType, and PredType.
class Attribute
Class Attribute operates on HDF5 attributes.
class AttributeIException
class CommonFG
CommonFG is an abstract base class of H5Group.
class CompType
CompType is a derivative of a DataType and operates on HDF5 compound datatypes.
class DataSet
Class DataSet operates on HDF5 datasets.
class DataSetIException
class DataSpace
Class DataSpace inherits from IdComponent and provides wrappers for the HDF5's dataspaces.
class DataSpaceIException
class DataType
Class DataType provides generic operations on HDF5 datatypes.
class DataTypeIException
class DSetAccPropList
Class DSetAccPropList inherits from LinkAccPropList and provides wrappers for the HDF5 dataset access property functions.
class DSetCreatPropList
Class DSetCreatPropList inherits from ObjCreatPropList and provides wrappers for the HDF5 dataset creation property functions.
class DSetMemXferPropList
Class DSetCreatPropList inherits from PropList and provides wrappers for the HDF5 dataset memory and transfer property list.
class EnumType
EnumType is a derivative of a DataType and operates on HDF5 enum datatypes.
class Exception
Exception provides wrappers of HDF5 error handling functions.
class FileAccPropList
Class FileAccPropList inherits from PropList and provides wrappers for the HDF5 file access property list.
class FileCreatPropList
Class FileCreatPropList inherits from PropList and provides wrappers for the HDF5 file create property list.
class FileIException
class FloatType
FloatType is a derivative of a DataType and operates on HDF5 floating point datatype.
class Group
Class Group represents an HDF5 group.
class GroupIException
class H5File
Class H5File represents an HDF5 file and inherits from class Group as file is a root group.
class H5Library
Class H5Library operates the HDF5 library globably.
class H5Location
H5Location is an abstract base class, added in version 1.8.12.
class H5Object
Class H5Object is a bridge between H5Location and DataSet, DataType, and Group.
class IdComponent
Class IdComponent provides wrappers of the C functions that operate on an HDF5 identifier.
class IdComponentException
class IntType
IntType is a derivative of a DataType and operates on HDF5 integer datatype.
class LibraryIException
class LinkAccPropList
Class LinkAccPropList inherits from PropList and provides wrappers for the HDF5 link access property list.
class LinkCreatPropList
Class LinkCreatPropList inherits from PropList and provides wrappers for the HDF5 link creation property list.
class LocationException
class ObjCreatPropList
Class ObjCreatPropList inherits from PropList and provides wrappers for the HDF5 object create property list.
class ObjHeaderIException
class PredType
Class PredType holds the definition of all the HDF5 predefined datatypes.
class PropList
Class PropList inherits from IdComponent and provides wrappers for the HDF5 generic property list.
class PropListIException
class ReferenceException
class StrType
StrType is a derivative of a DataType and operates on HDF5 string datatype.
class UserData4Aiterate
class UserData4Visit
class VarLenType
VarLenType is a derivative of a DataType and operates on HDF5 Variable-length Datatypes.
Typedefs
typedef void(* attr_operator_t) (H5Object &loc, const H5std_string attr_name, void *operator_data)
typedef int(* visit_operator_t) (H5Object &obj, const H5std_string attr_name, const H5O_info2_t *oinfo, void *operator_data)
Functions
void f_DataSpace_setId (DataSpace *dspace, hid_t new_id)
Typedef Documentation
attr_operator_t
typedef void(* H5::attr_operator_t) (H5Object &loc, const H5std_string attr_name, void *operator_data)
visit_operator_t
typedef int(* H5::visit_operator_t) (H5Object &obj, const H5std_string attr_name, const H5O_info2_t *oinfo, void *operator_data)
Function Documentation
f_DataSpace_setId()
void H5::f_DataSpace_setId (DataSpace * dspace, hid_t new_id)
Referenced by H5::H5Location::getRegion(), H5::Attribute::getSpace(), and H5::DataSet::getSpace().
The HDF Group Help Desk:
Copyright by The HDF Group
and the Board of Trustees of the University of Illinois